// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

namespace Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220602022409_AddedThePostModel")]
    partial class AddedThePostModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.6.21352.1");

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImagePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            Description = "A description of category 1",
                            Name = "Category 1",
                            ThumbnailImagePath = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            categoryId = 2,
                            Description = "A description of category 2",
                            Name = "Category 2",
                            ThumbnailImagePath = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            categoryId = 3,
                            Description = "A description of category 3",
                            Name = "Category 3",
                            ThumbnailImagePath = "uploads/placeholder.jpg"
                        });
                });

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailImagePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId");

                    b.HasIndex("categoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Author = "Breno Trindade",
                            Content = "",
                            Excerpt = "This is the excerpt for opst 1. An excerpt is a little extration from a larger piece of text. Sort of like a preview.",
                            PublishDate = "02/06/2022 02:24",
                            Published = true,
                            ThumbnailImagePath = "uploads/placeholder.jpg",
                            Title = "First post",
                            categoryId = 1
                        },
                        new
                        {
                            PostId = 2,
                            Author = "Breno Trindade",
                            Content = "",
                            Excerpt = "This is the excerpt for opst 2. An excerpt is a little extration from a larger piece of text. Sort of like a preview.",
                            PublishDate = "02/06/2022 02:24",
                            Published = true,
                            ThumbnailImagePath = "uploads/placeholder.jpg",
                            Title = "Second post",
                            categoryId = 2
                        },
                        new
                        {
                            PostId = 3,
                            Author = "Breno Trindade",
                            Content = "",
                            Excerpt = "This is the excerpt for opst 3. An excerpt is a little extration from a larger piece of text. Sort of like a preview.",
                            PublishDate = "02/06/2022 02:24",
                            Published = true,
                            ThumbnailImagePath = "uploads/placeholder.jpg",
                            Title = "Third post",
                            categoryId = 3
                        },
                        new
                        {
                            PostId = 4,
                            Author = "Breno Trindade",
                            Content = "",
                            Excerpt = "This is the excerpt for opst 4. An excerpt is a little extration from a larger piece of text. Sort of like a preview.",
                            PublishDate = "02/06/2022 02:24",
                            Published = true,
                            ThumbnailImagePath = "uploads/placeholder.jpg",
                            Title = "Fourth post",
                            categoryId = 1
                        },
                        new
                        {
                            PostId = 5,
                            Author = "Breno Trindade",
                            Content = "",
                            Excerpt = "This is the excerpt for opst 5. An excerpt is a little extration from a larger piece of text. Sort of like a preview.",
                            PublishDate = "02/06/2022 02:24",
                            Published = true,
                            ThumbnailImagePath = "uploads/placeholder.jpg",
                            Title = "Fifith post",
                            categoryId = 2
                        },
                        new
                        {
                            PostId = 6,
                            Author = "Breno Trindade",
                            Content = "",
                            Excerpt = "This is the excerpt for opst 6. An excerpt is a little extration from a larger piece of text. Sort of like a preview.",
                            PublishDate = "02/06/2022 02:24",
                            Published = true,
                            ThumbnailImagePath = "uploads/placeholder.jpg",
                            Title = "Sixth post",
                            categoryId = 3
                        });
                });

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.HasOne("Shared.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
